name: 部署到 ECS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 设置 Node.js 环境
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: 安装依赖
        run: npm install --frozen-lockfile

      - name: 构建 Docusaurus
        run: npm run build

      - name: ssh-scp-deploy
        uses: marcodallasanta/ssh-scp-deploy@v1.2.0
        with:
          local: build
          remote: /usr/local/nginx/html
          host: ${{ secrets.REMOTE_HOST }}
          user: ${{ secrets.REMOTE_USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          post_upload: sudo nginx -s reload
